apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: musicin
  labels:
    app: musicin-web
spec:
  type: NodePort
  selector:
    app: musicin-web
  ports:
    - protocol: TCP
      port: 80