apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicindb-pvc
  namespace: musicin
  labels:
    app: musicin-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
